[package]
name = "rip-eth-key"
authors = ["Willem Olding <willemolding@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
secp256k1 = "0.20.3"
sliding_windows = "3.0.0"
structopt = "0.3.23"
