[package]
name = "rip-eth-key"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.20.3"
sliding_windows = "3.0.0"
structopt = "0.3.23"
